name: jimtl
description: Intl utility to use ARB files without code generation, deal with ARB flavors and have ARB OTA updates in your app
version: 0.0.7
homepage: https://github.com/jaumard/jimtl

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  intl: ">=0.17.0 <1.0.0"
  intl_generator:
    git:
      url: git@github.com:Elr03/intl_generator.git

dev_dependencies:
  test:
